// <auto-generated />
namespace Medlebox.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UsersMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsersMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201308211650507_UsersMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
